name: intellilotto
description: 智能彩選應用程式

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  dart_openai: ^5.1.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  line_icons: ^2.0.3
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
